Algoritmo "Combinacoes"
//
//
// Descrição   : Combinacao entre 1 e 3 em dois digitos.
// Autor(a)    : Giovanni P Goulart
// Data atual  : 14/07/2022
Var
   // Seção de Declarações das variáveis
   C1, C2: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para C1 := 1 ate 3 faca
      Para C2 := 1 ate 3 faca
         Escreval (C1, C2)
      FimPara
   FimPara
Fimalgoritmo