Algoritmo "Contar 10 a 0"
// 
//  
// Descrição   : Contar de 10 ate 0.
// Autor(a)    : Giovanni P.Goulart
// Data atual  : 12/07/2022
Var
// Seção de Declarações das variáveis 
  contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      contador<- 10
      Enquanto (contador >=0) faca
      Escreval (contador)
      contador <- contador -1
      FimEnquanto
      Escreval ( " Terminei de contar " )

Fimalgoritmo