Algoritmo "Conte ate 10"
// 
//  
// Descrição   : Contar de zero ate 10
// Autor(a)    : Giovanni P.Goulart
// Data atual  : 12/07/2022
Var
// Seção de Declarações das variáveis 
 contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  contador <- 0

  Enquanto (contador <=10) faca
  Escreval (contador)
  contador <- contador + 1
  FimEnquanto
  Escreval (" Terminei de contar ")
  

Fimalgoritmo