Algoritmo "Creuza01"
// 
//  
// Descrição   : Revisao
// Autor(a)    : Giovanni
// Data atual  : 05/07/2022
Var
// Seção de Declarações das variáveis 
 ano_atual, ano_nasc, idade: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Em que ano nos estamos?")
 Leia(ano_atual)
 Escreva("Em que ano eu nasci?")
 Leia (ano_nasc)
 idade<-ano_atual - ano_nasc
 Escreva ("Minha idade sera", idade)
Fimalgoritmo