Algoritmo "Creuza02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Giovanni
// Data atual  : 05/07/2022
Var
// Seção de Declarações das variáveis 
reais, dolares: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreva("Quantos reais eu tenho? R$")
  Leia (reais)
  dolares<- reais/2.20
  Escreva ("Posso ter US$", dolares)


Fimalgoritmo